# Generated by Django 5.2.4 on 2025-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('sku', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
