# Generated by Django 5.2.4 on 2025-07-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppShop', '0002_contacto_registrarse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrarse',
            new_name='clientes',
        ),
    ]
