# Generated by Django 5.2.4 on 2025-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShop', '0005_mensajecontacto_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
